parameters:
    media_image_service: ByHours\MediaBundle\Services\ImageService

services:
#    media.example:
#        class: ByHours\MediaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  media_image_service:
        class:  %media_image_service%
        arguments:  [ @router, @security.context,@doctrine.orm.entity_manager, @form.factory]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
