inventory:
    path:     /
    defaults: { _controller: "StampiAdminBundle:Inventory:index" }

inventory_show:
    path:     /{id}/show
    defaults: { _controller: "StampiAdminBundle:Inventory:show" }

inventory_new:
    path:     /new
    defaults: { _controller: "StampiAdminBundle:Inventory:new" }

inventory_create:
    path:     /create
    defaults: { _controller: "StampiAdminBundle:Inventory:create" }
    requirements: { _method: post }

inventory_edit:
    path:     /{id}/edit
    defaults: { _controller: "StampiAdminBundle:Inventory:edit" }

inventory_update:
    path:     /{id}/update
    defaults: { _controller: "StampiAdminBundle:Inventory:update" }
    requirements: { _method: post|put }

inventory_delete:
    path:     /{id}/delete
    defaults: { _controller: "StampiAdminBundle:Inventory:delete" }
    requirements: { _method: post|delete }
