<?php

namespace Stampi\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextI18nRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextI18nRepository extends EntityRepository
{
}
